version: "3.8"

services:
    mongo-service:
        container_name: mongo-service
        image: mongo:4.4.0
        volumes: 
            - ./services/mongo-service/db:/data/db
            - ./services/mongo-service/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - PODCAST_PARTS_DB_NAME=${PODCAST_PARTS_DB_NAME}
            - PODCAST_PARTS_DB_USER=${PODCAST_PARTS_DB_USER}
            - PODCAST_PARTS_DB_PASSWORD=${PODCAST_PARTS_DB_PASSWORD}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:27017"]
            interval: 10s
            timeout: 10s
            retries: 5
    
    podcast-parts-service:
        container_name: podcast-parts-service
        image: "node:12.18"
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./services/podcast-parts-service:/home/node/app
        expose: 
            - ${PODCAST_PARTS_SERVICE_EXPOSED_PORT}
        ports:
            - "${PODCAST_PARTS_SERVICE_EXPOSED_PORT}:${PODCAST_PARTS_SERVICE_EXPOSED_PORT}"
        environment: 
            - NODE_ENV=${NODE_ENV}
            - MONGO_DB_HOST=${MONGO_DB_HOST}
            - MONGO_DB_PORT=${MONGO_DB_PORT}
            - PODCAST_PARTS_DB_NAME=${PODCAST_PARTS_DB_NAME}
            - PODCAST_PARTS_DB_USER=${PODCAST_PARTS_DB_USER}
            - PODCAST_PARTS_DB_PASSWORD=${PODCAST_PARTS_DB_PASSWORD}
            - PODCAST_PARTS_SERVICE_EXPOSED_PORT=${PODCAST_PARTS_SERVICE_EXPOSED_PORT}
        command: ./run.sh
        links:
            - mongo-service      
        
    storage-service:
        container_name: storage-service
        image: "node:12.18"
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./services/storage-service:/home/node/app
        expose: 
            - ${STORAGE_SERVICE_EXPOSED_PORT}
        ports:
            - "${STORAGE_SERVICE_EXPOSED_PORT}:${STORAGE_SERVICE_EXPOSED_PORT}"
        environment: 
            - NODE_ENV=${NODE_ENV}
            - MONGO_DB_HOST=${MONGO_DB_HOST}
            - MONGO_DB_PORT=${MONGO_DB_PORT}
            - PODCAST_PARTS_DB_NAME=${PODCAST_PARTS_DB_NAME}
            - PODCAST_PARTS_DB_USER=${PODCAST_PARTS_DB_USER}
            - PODCAST_PARTS_DB_PASSWORD=${PODCAST_PARTS_DB_PASSWORD}
            - STORAGE_SERVICE_EXPOSED_PORT=${STORAGE_SERVICE_EXPOSED_PORT}
            - SCALEWAY_BUCKET_NAME=${SCALEWAY_BUCKET_NAME}
            - SCALEWAY_REGION=${SCALEWAY_REGION}
            - SCALEWAY_ENDPOINT=${SCALEWAY_ENDPOINT}
            - SCALEWAY_ACCESS_KEY_ID=${SCALEWAY_ACCESS_KEY_ID}
            - SCALEWAY_SECRET_ACCESS_KEY=${SCALEWAY_SECRET_ACCESS_KEY}
            - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
            - AWS_REGION=${AWS_REGION}
            - AWS_ENDPOINT=${AWS_ENDPOINT}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: ./run.sh
        links:
            - mongo-service     