version: "3.8"

services:
    mongo-service:
        image: mongo:4.4.0
        volumes: 
            - ./services/mongo-service/db:/data/db
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:27017"]
            interval: 10s
            timeout: 10s
            retries: 5
    
    podcast-parts-service:
        image: "node:12.18"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./services/podcast-parts-service:/home/node/app
        expose: 
            - ${PODCAST_PARTS_SERVICE_EXPOSED_PORT}
        ports:
            - "${PODCAST_PARTS_SERVICE_EXPOSED_PORT}:${PODCAST_PARTS_SERVICE_EXPOSED_PORT}"
        environment: 
            - NODE_ENV=${NODE_ENV}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - PODCAST_PARTS_SERVICE_EXPOSED_PORT=${PODCAST_PARTS_SERVICE_EXPOSED_PORT}
        command: ./run.sh
        links:
            - mongo-service      