export const WORKER_STATUS_AVAILABLE = 'available';
export const WORKER_STATUS_BUSY = 'busy';

export const WORKER_STATES = [WORKER_STATUS_AVAILABLE, WORKER_STATUS_BUSY];

export default {
  WORKER_STATES,
  WORKER_STATUS_AVAILABLE,
  WORKER_STATUS_BUSY
};
